# This is a basic workflow to help you get started with Actions
name: Deploy
on:
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: '8.1'

      - name: Get Composer
        run: bash get_composer.bash

      # Runs a single command using the runners shell
      - name: Build Pattern Library
        run: bash build_pattern_lib.bash

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: storybook-static
