name: Deploy
on:
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: '8.1'

      - name: Get Composer
        run: bash get_composer.bash

      - name: Build Pattern Library
        run: bash build_pattern_lib.bash

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: storybook-static
